platform :ios, '8.0'

target 'WKFinanceDemo' do

pod 'SBLib',:git=>"https://github.com/doll313/SBLib", :tag=>'0.8.4'
pod 'WKChewieRefresh'
pod 'Masonry'
pod 'SDCycleScrollView', '~> 1.74'
pod 'WRNavigationBar','~>1.0.9'
end
